### Initialize Data
POST http://localhost:8080/admin/initialization

### Delete data
DELETE http://localhost:8080

### Catalog
GET http://localhost:8080/orders

###
GET http://localhost:8080/orders/2

### Place order
POST http://localhost:8080/orders
Content-Type: application/json

{
  "items": [
    {
      "bookId": 26,
      "quantity": 1
    },
    {
      "bookId": 13,
      "quantity": 1
    }
  ],
  "recipient": {
    "name": "Mat Erna",
    "phone": "123-456-789",
    "street": "Cwiartki 3/10",
    "city": "Zakopane",
    "zipCode": "30-150",
    "email": "mateusz@v.com"
  }
}


###
PUT http://localhost:8080/orders/1/status
Content-Type: application/json

{
  "status": "CANCELED"
}
